engines:
  rubocop:
    enabled: true
  brakeman:
    enabled: true
  eslint:
    enabled: true
  csslint:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
      - ruby
      - javascript
ratings:
  paths:
  - app/**
  - lib/**
  - "**.rb"
  - "**.js"
exclude_paths:
- bin/**/*
- db/**/*
- doc/**/*
- public/**/*
- spec/**/*
- vendor/**/*

